# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!

import sys
import os
if hasattr(sys, 'frozen'):  # PyQt5打包有bug需要自己设定PATH
    os.environ['PATH'] = sys._MEIPASS + ";" + os.environ['PATH']
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_main_window(object):
    def setupUi(self, main_window):
        main_window.setObjectName("main_window")
        main_window.resize(693, 547)
        main_window.setMinimumSize(QtCore.QSize(693, 547))
        main_window.setMaximumSize(QtCore.QSize(693, 547))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("CSOC.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        main_window.setWindowIcon(icon)
        self.centralWidget = QtWidgets.QWidget(main_window)
        self.centralWidget.setObjectName("centralWidget")
        self.group_box_data_and_save = QtWidgets.QGroupBox(self.centralWidget)
        self.group_box_data_and_save.setGeometry(QtCore.QRect(20, 40, 321, 211))
        self.group_box_data_and_save.setObjectName("group_box_data_and_save")
        self.line_edit_excel = QtWidgets.QLineEdit(self.group_box_data_and_save)
        self.line_edit_excel.setGeometry(QtCore.QRect(40, 60, 181, 20))
        self.line_edit_excel.setObjectName("line_edit_excel")
        self.label_excel = QtWidgets.QLabel(self.group_box_data_and_save)
        self.label_excel.setGeometry(QtCore.QRect(40, 40, 151, 16))
        self.label_excel.setObjectName("label_excel")
        self.tool_button_find_excel = QtWidgets.QToolButton(self.group_box_data_and_save)
        self.tool_button_find_excel.setGeometry(QtCore.QRect(240, 60, 41, 21))
        self.tool_button_find_excel.setObjectName("tool_button_find_excel")
        self.label_train_result = QtWidgets.QLabel(self.group_box_data_and_save)
        self.label_train_result.setGeometry(QtCore.QRect(40, 90, 251, 16))
        self.label_train_result.setObjectName("label_train_result")
        self.tool_button_save_train_result = QtWidgets.QToolButton(self.group_box_data_and_save)
        self.tool_button_save_train_result.setGeometry(QtCore.QRect(240, 110, 41, 21))
        self.tool_button_save_train_result.setObjectName("tool_button_save_train_result")
        self.line_edit_train_result = QtWidgets.QLineEdit(self.group_box_data_and_save)
        self.line_edit_train_result.setGeometry(QtCore.QRect(40, 110, 181, 20))
        self.line_edit_train_result.setObjectName("line_edit_train_result")
        self.line_edit_c_fun = QtWidgets.QLineEdit(self.group_box_data_and_save)
        self.line_edit_c_fun.setGeometry(QtCore.QRect(40, 160, 181, 20))
        self.line_edit_c_fun.setObjectName("line_edit_c_fun")
        self.tool_button_save_c_fun = QtWidgets.QToolButton(self.group_box_data_and_save)
        self.tool_button_save_c_fun.setGeometry(QtCore.QRect(240, 160, 41, 21))
        self.tool_button_save_c_fun.setObjectName("tool_button_save_c_fun")
        self.label_c_fun = QtWidgets.QLabel(self.group_box_data_and_save)
        self.label_c_fun.setGeometry(QtCore.QRect(40, 140, 161, 16))
        self.label_c_fun.setObjectName("label_c_fun")
        self.group_box_train_data = QtWidgets.QGroupBox(self.centralWidget)
        self.group_box_train_data.setGeometry(QtCore.QRect(360, 40, 311, 211))
        self.group_box_train_data.setObjectName("group_box_train_data")
        self.label_r = QtWidgets.QLabel(self.group_box_train_data)
        self.label_r.setGeometry(QtCore.QRect(40, 20, 81, 21))
        self.label_r.setObjectName("label_r")
        self.line_edit_r = QtWidgets.QLineEdit(self.group_box_train_data)
        self.line_edit_r.setGeometry(QtCore.QRect(140, 20, 41, 20))
        self.line_edit_r.setObjectName("line_edit_r")
        self.line_edit_soc = QtWidgets.QLineEdit(self.group_box_train_data)
        self.line_edit_soc.setEnabled(False)
        self.line_edit_soc.setGeometry(QtCore.QRect(140, 50, 41, 20))
        self.line_edit_soc.setObjectName("line_edit_soc")
        self.label_soc = QtWidgets.QLabel(self.group_box_train_data)
        self.label_soc.setGeometry(QtCore.QRect(40, 50, 81, 21))
        self.label_soc.setObjectName("label_soc")
        self.line_edit_c = QtWidgets.QLineEdit(self.group_box_train_data)
        self.line_edit_c.setGeometry(QtCore.QRect(140, 110, 41, 20))
        self.line_edit_c.setObjectName("line_edit_c")
        self.label_c = QtWidgets.QLabel(self.group_box_train_data)
        self.label_c.setGeometry(QtCore.QRect(40, 110, 81, 21))
        self.label_c.setObjectName("label_c")
        self.check_box_choose_t = QtWidgets.QCheckBox(self.group_box_train_data)
        self.check_box_choose_t.setEnabled(True)
        self.check_box_choose_t.setGeometry(QtCore.QRect(200, 80, 91, 21))
        self.check_box_choose_t.setObjectName("check_box_choose_t")
        self.line_edit_t = QtWidgets.QLineEdit(self.group_box_train_data)
        self.line_edit_t.setEnabled(False)
        self.line_edit_t.setGeometry(QtCore.QRect(140, 80, 41, 20))
        self.line_edit_t.setAutoFillBackground(False)
        self.line_edit_t.setReadOnly(False)
        self.line_edit_t.setObjectName("line_edit_t")
        self.label_t = QtWidgets.QLabel(self.group_box_train_data)
        self.label_t.setGeometry(QtCore.QRect(40, 80, 81, 21))
        self.label_t.setObjectName("label_t")
        self.line_edit_soh = QtWidgets.QLineEdit(self.group_box_train_data)
        self.line_edit_soh.setEnabled(False)
        self.line_edit_soh.setGeometry(QtCore.QRect(140, 140, 41, 20))
        self.line_edit_soh.setObjectName("line_edit_soh")
        self.label_soh = QtWidgets.QLabel(self.group_box_train_data)
        self.label_soh.setGeometry(QtCore.QRect(40, 140, 81, 21))
        self.label_soh.setObjectName("label_soh")
        self.check_box_choose_soc = QtWidgets.QCheckBox(self.group_box_train_data)
        self.check_box_choose_soc.setGeometry(QtCore.QRect(200, 50, 91, 21))
        self.check_box_choose_soc.setObjectName("check_box_choose_soc")
        self.push_button_correlation = QtWidgets.QPushButton(self.group_box_train_data)
        self.push_button_correlation.setGeometry(QtCore.QRect(120, 170, 75, 23))
        self.push_button_correlation.setObjectName("push_button_correlation")
        self.radio_button_choose_c = QtWidgets.QRadioButton(self.group_box_train_data)
        self.radio_button_choose_c.setEnabled(True)
        self.radio_button_choose_c.setGeometry(QtCore.QRect(200, 110, 91, 21))
        self.radio_button_choose_c.setCheckable(True)
        self.radio_button_choose_c.setChecked(True)
        self.radio_button_choose_c.setAutoRepeat(False)
        self.radio_button_choose_c.setObjectName("radio_button_choose_c")
        self.radio_button_choose_soh = QtWidgets.QRadioButton(self.group_box_train_data)
        self.radio_button_choose_soh.setGeometry(QtCore.QRect(200, 140, 91, 21))
        self.radio_button_choose_soh.setObjectName("radio_button_choose_soh")
        self.push_button_about_train_data = QtWidgets.QPushButton(self.group_box_train_data)
        self.push_button_about_train_data.setGeometry(QtCore.QRect(290, 10, 16, 21))
        self.push_button_about_train_data.setMouseTracking(False)
        self.push_button_about_train_data.setAcceptDrops(False)
        self.push_button_about_train_data.setAutoFillBackground(False)
        self.push_button_about_train_data.setObjectName("push_button_about_train_data")
        self.group_box_ann = QtWidgets.QGroupBox(self.centralWidget)
        self.group_box_ann.setGeometry(QtCore.QRect(20, 260, 321, 231))
        self.group_box_ann.setObjectName("group_box_ann")
        self.label_neuron = QtWidgets.QLabel(self.group_box_ann)
        self.label_neuron.setGeometry(QtCore.QRect(70, 20, 181, 21))
        self.label_neuron.setObjectName("label_neuron")
        self.line_edit_neuron = QtWidgets.QLineEdit(self.group_box_ann)
        self.line_edit_neuron.setGeometry(QtCore.QRect(60, 40, 201, 20))
        self.line_edit_neuron.setObjectName("line_edit_neuron")
        self.label_epochs = QtWidgets.QLabel(self.group_box_ann)
        self.label_epochs.setGeometry(QtCore.QRect(90, 70, 61, 21))
        self.label_epochs.setObjectName("label_epochs")
        self.line_edit_epochs = QtWidgets.QLineEdit(self.group_box_ann)
        self.line_edit_epochs.setGeometry(QtCore.QRect(170, 70, 61, 20))
        self.line_edit_epochs.setObjectName("line_edit_epochs")
        self.line_edit_mini_batch_size = QtWidgets.QLineEdit(self.group_box_ann)
        self.line_edit_mini_batch_size.setGeometry(QtCore.QRect(170, 100, 61, 20))
        self.line_edit_mini_batch_size.setObjectName("line_edit_mini_batch_size")
        self.label_minibatchsize = QtWidgets.QLabel(self.group_box_ann)
        self.label_minibatchsize.setGeometry(QtCore.QRect(70, 100, 91, 21))
        self.label_minibatchsize.setObjectName("label_minibatchsize")
        self.line_edit_eta = QtWidgets.QLineEdit(self.group_box_ann)
        self.line_edit_eta.setGeometry(QtCore.QRect(170, 130, 61, 20))
        self.line_edit_eta.setObjectName("line_edit_eta")
        self.label_eta = QtWidgets.QLabel(self.group_box_ann)
        self.label_eta.setGeometry(QtCore.QRect(100, 130, 51, 16))
        self.label_eta.setObjectName("label_eta")
        self.push_button_ann = QtWidgets.QPushButton(self.group_box_ann)
        self.push_button_ann.setGeometry(QtCore.QRect(120, 190, 75, 23))
        self.push_button_ann.setObjectName("push_button_ann")
        self.push_button_about_ann = QtWidgets.QPushButton(self.group_box_ann)
        self.push_button_about_ann.setGeometry(QtCore.QRect(300, 10, 16, 21))
        self.push_button_about_ann.setMouseTracking(False)
        self.push_button_about_ann.setAcceptDrops(False)
        self.push_button_about_ann.setAutoFillBackground(False)
        self.push_button_about_ann.setObjectName("push_button_about_ann")
        self.label_act = QtWidgets.QLabel(self.group_box_ann)
        self.label_act.setGeometry(QtCore.QRect(90, 160, 61, 21))
        self.label_act.setObjectName("label_act")
        self.combo_box_act = QtWidgets.QComboBox(self.group_box_ann)
        self.combo_box_act.setGeometry(QtCore.QRect(160, 160, 81, 22))
        self.combo_box_act.setObjectName("combo_box_act")
        self.combo_box_act.addItem("")
        self.combo_box_act.addItem("")
        self.combo_box_act.addItem("")
        self.combo_box_act.addItem("")
        self.group_box_line = QtWidgets.QGroupBox(self.centralWidget)
        self.group_box_line.setGeometry(QtCore.QRect(360, 260, 311, 91))
        self.group_box_line.setObjectName("group_box_line")
        self.spin_box_order = QtWidgets.QSpinBox(self.group_box_line)
        self.spin_box_order.setGeometry(QtCore.QRect(180, 20, 42, 22))
        self.spin_box_order.setMinimum(1)
        self.spin_box_order.setMaximum(5)
        self.spin_box_order.setObjectName("spin_box_order")
        self.label_order = QtWidgets.QLabel(self.group_box_line)
        self.label_order.setGeometry(QtCore.QRect(80, 20, 81, 21))
        self.label_order.setObjectName("label_order")
        self.push_button_line = QtWidgets.QPushButton(self.group_box_line)
        self.push_button_line.setGeometry(QtCore.QRect(110, 60, 75, 23))
        self.push_button_line.setObjectName("push_button_line")
        self.push_button_help = QtWidgets.QPushButton(self.centralWidget)
        self.push_button_help.setGeometry(QtCore.QRect(560, 10, 75, 23))
        self.push_button_help.setObjectName("push_button_help")
        self.text_browser_tips = QtWidgets.QTextBrowser(self.centralWidget)
        self.text_browser_tips.setGeometry(QtCore.QRect(360, 360, 311, 131))
        self.text_browser_tips.setObjectName("text_browser_tips")
        main_window.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(main_window)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 693, 23))
        self.menuBar.setObjectName("menuBar")
        main_window.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(main_window)
        self.mainToolBar.setObjectName("mainToolBar")
        main_window.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(main_window)
        self.statusBar.setObjectName("statusBar")
        main_window.setStatusBar(self.statusBar)

        self.retranslateUi(main_window)
        self.combo_box_act.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(main_window)
        main_window.setTabOrder(self.push_button_help, self.tool_button_find_excel)
        main_window.setTabOrder(self.tool_button_find_excel, self.line_edit_excel)
        main_window.setTabOrder(self.line_edit_excel, self.tool_button_save_train_result)
        main_window.setTabOrder(self.tool_button_save_train_result, self.line_edit_train_result)
        main_window.setTabOrder(self.line_edit_train_result, self.tool_button_save_c_fun)
        main_window.setTabOrder(self.tool_button_save_c_fun, self.line_edit_c_fun)
        main_window.setTabOrder(self.line_edit_c_fun, self.push_button_about_train_data)
        main_window.setTabOrder(self.push_button_about_train_data, self.line_edit_r)
        main_window.setTabOrder(self.line_edit_r, self.check_box_choose_soc)
        main_window.setTabOrder(self.check_box_choose_soc, self.line_edit_soc)
        main_window.setTabOrder(self.line_edit_soc, self.check_box_choose_t)
        main_window.setTabOrder(self.check_box_choose_t, self.line_edit_t)
        main_window.setTabOrder(self.line_edit_t, self.radio_button_choose_c)
        main_window.setTabOrder(self.radio_button_choose_c, self.line_edit_c)
        main_window.setTabOrder(self.line_edit_c, self.radio_button_choose_soh)
        main_window.setTabOrder(self.radio_button_choose_soh, self.line_edit_soh)
        main_window.setTabOrder(self.line_edit_soh, self.push_button_correlation)
        main_window.setTabOrder(self.push_button_correlation, self.push_button_about_ann)
        main_window.setTabOrder(self.push_button_about_ann, self.line_edit_neuron)
        main_window.setTabOrder(self.line_edit_neuron, self.line_edit_epochs)
        main_window.setTabOrder(self.line_edit_epochs, self.line_edit_mini_batch_size)
        main_window.setTabOrder(self.line_edit_mini_batch_size, self.line_edit_eta)
        main_window.setTabOrder(self.line_edit_eta, self.push_button_ann)
        main_window.setTabOrder(self.push_button_ann, self.spin_box_order)
        main_window.setTabOrder(self.spin_box_order, self.push_button_line)
        main_window.setTabOrder(self.push_button_line, self.text_browser_tips)

    def retranslateUi(self, main_window):
        _translate = QtCore.QCoreApplication.translate
        main_window.setWindowTitle(_translate("main_window", "锂离子电池容量估算平台V1.3"))
        self.group_box_data_and_save.setTitle(_translate("main_window", "训练数据与保存结果"))
        self.label_excel.setText(_translate("main_window", "请选择你的Excel数据文件："))
        self.tool_button_find_excel.setText(_translate("main_window", "..."))
        self.label_train_result.setText(_translate("main_window", "请选择你要保存训练结果及相关性分析的位置："))
        self.tool_button_save_train_result.setText(_translate("main_window", "..."))
        self.tool_button_save_c_fun.setText(_translate("main_window", "..."))
        self.label_c_fun.setText(_translate("main_window", "请选择你要保存C函数的位置："))
        self.group_box_train_data.setTitle(_translate("main_window", "训练数据设置"))
        self.label_r.setText(_translate("main_window", "电阻所在列数："))
        self.label_soc.setText(_translate("main_window", "SOC所在列数："))
        self.label_c.setText(_translate("main_window", "容量所在列数："))
        self.check_box_choose_t.setText(_translate("main_window", "使用该自变量"))
        self.label_t.setText(_translate("main_window", "温度所在列数："))
        self.label_soh.setText(_translate("main_window", "SOH所在列数："))
        self.check_box_choose_soc.setText(_translate("main_window", "使用该自变量"))
        self.push_button_correlation.setText(_translate("main_window", "相关性分析"))
        self.radio_button_choose_c.setText(_translate("main_window", "使用该因变量"))
        self.radio_button_choose_soh.setText(_translate("main_window", "使用该因变量"))
        self.push_button_about_train_data.setText(_translate("main_window", "?"))
        self.group_box_ann.setTitle(_translate("main_window", "神经网络训练"))
        self.label_neuron.setText(_translate("main_window", "神经网络每个隐藏层神经元数量："))
        self.label_epochs.setText(_translate("main_window", "训练次数："))
        self.label_minibatchsize.setText(_translate("main_window", "每次训练样本数："))
        self.label_eta.setText(_translate("main_window", "学习率："))
        self.push_button_ann.setText(_translate("main_window", "开始训练"))
        self.push_button_about_ann.setText(_translate("main_window", "?"))
        self.label_act.setText(_translate("main_window", "激活函数："))
        self.combo_box_act.setItemText(0, _translate("main_window", "Sigmoid"))
        self.combo_box_act.setItemText(1, _translate("main_window", "tanh"))
        self.combo_box_act.setItemText(2, _translate("main_window", "ReLU"))
        self.combo_box_act.setItemText(3, _translate("main_window", "Leaky ReLU"))
        self.group_box_line.setTitle(_translate("main_window", "线性拟合"))
        self.label_order.setText(_translate("main_window", "线性拟合阶数："))
        self.push_button_line.setText(_translate("main_window", "开始拟合"))
        self.push_button_help.setText(_translate("main_window", "帮助"))
